import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const docsDir = resolve(root, 'docs/balance');

const phases = [
  {
    id: 'phase-1',
    name: 'First Click / First Item',
    window: '0-5 min',
    buds: '80-650',
    bps: '0.2-5',
    bpc: '1-3',
    items: '1-6',
    upgrades: '0-1',
    research: '0',
    events: '0-1',
    seeds: '0',
    prestige: '0',
    activeShare: '80%',
  },
  {
    id: 'phase-2',
    name: 'Early Automation',
    window: '5-30 min',
    buds: '5k-180k',
    bps: '35-1.8k',
    bpc: '5-28',
    items: '18-80',
    upgrades: '3-12',
    research: '0-3',
    events: '2-7',
    seeds: '0-2',
    prestige: '0',
    activeShare: '55-70%',
  },
  {
    id: 'phase-3',
    name: 'First Strategy',
    window: '30-90 min',
    buds: '300k-6M',
    bps: '3k-55k',
    bpc: '35-180',
    items: '85-260',
    upgrades: '12-28',
    research: '4-14',
    events: '8-20',
    seeds: '2-8',
    prestige: '0-1 ready',
    activeShare: '35-55%',
  },
  {
    id: 'phase-4',
    name: 'Post-Prestige Acceleration',
    window: '1.5-4 h',
    buds: '8M-180M',
    bps: '80k-1.5M',
    bpc: '220-900',
    items: '240-620',
    upgrades: '25-52',
    research: '12-28',
    events: '18-55',
    seeds: '8-35',
    prestige: '1-3',
    activeShare: '25-45%',
  },
  {
    id: 'phase-5',
    name: 'Release Midgame',
    window: '4-10 h',
    buds: '220M-18B',
    bps: '2M-110M',
    bpc: '1.2k-9k',
    items: '620-1.4k',
    upgrades: '48-82',
    research: '26-44',
    events: '55-140',
    seeds: '35-130',
    prestige: '3-8',
    activeShare: '18-35%',
  },
  {
    id: 'phase-6',
    name: 'Long Release Tail',
    window: '10-20 h',
    buds: '20B-2T',
    bps: '130M-9B',
    bpc: '10k-80k',
    items: '1.4k-2.4k',
    upgrades: '75-100+',
    research: '42-51',
    events: '140-300',
    seeds: '130-450',
    prestige: '8-18',
    activeShare: '10-25%',
  },
];

const profiles = [
  {
    name: 'Active new player',
    clicksPerMinute: 105,
    eventCatch: 0.82,
    idleRatio: 0.25,
    prestigeBias: 1,
  },
  {
    name: 'Semi-idle player',
    clicksPerMinute: 22,
    eventCatch: 0.38,
    idleRatio: 0.72,
    prestigeBias: 0.86,
  },
  {
    name: 'Optimizer',
    clicksPerMinute: 72,
    eventCatch: 0.9,
    idleRatio: 0.18,
    prestigeBias: 1.18,
  },
  {
    name: 'Event-focused player',
    clicksPerMinute: 58,
    eventCatch: 0.96,
    idleRatio: 0.22,
    prestigeBias: 1.08,
  },
  {
    name: 'Prestige-oriented player',
    clicksPerMinute: 45,
    eventCatch: 0.66,
    idleRatio: 0.36,
    prestigeBias: 1.26,
  },
  {
    name: 'Mobile player',
    clicksPerMinute: 65,
    eventCatch: 0.68,
    idleRatio: 0.34,
    prestigeBias: 0.98,
  },
];

const checkpoints = [30, 90, 240, 600, 1200];

const rows = profiles.flatMap((profile) =>
  checkpoints.map((minutes) => {
    const activeFactor = Math.max(0.35, profile.clicksPerMinute / 80);
    const eventFactor = 1 + profile.eventCatch * 0.28;
    const idleFactor = 1 + profile.idleRatio * 0.22;
    const prestigeFactor = Math.pow(profile.prestigeBias, Math.max(0, Math.log2(minutes / 60)));
    const runScore = activeFactor * eventFactor * idleFactor * prestigeFactor;
    const prestigeCount = Math.max(0, Math.floor((minutes - 78) / 92 * profile.prestigeBias));
    const seeds = Math.max(0, Math.floor(Math.pow(minutes / 40, 1.42) * 2.8 * profile.prestigeBias));
    const bps = Math.floor(Math.pow(minutes, 2.24) * 3.8 * runScore);
    const buds = Math.floor(bps * minutes * 24 * (1 + prestigeCount * 0.18));
    const research = Math.min(51, Math.floor(Math.pow(minutes / 42, 1.08) * 4.2 * profile.prestigeBias));
    return {
      profile: profile.name,
      minutes,
      buds,
      bps,
      seeds,
      prestigeCount,
      research,
      events: Math.floor((minutes / 8) * profile.eventCatch),
    };
  }),
);

mkdirSync(docsDir, { recursive: true });
writeFileSync(resolve(docsDir, 'phase-targets-2-20h.md'), renderPhaseTargets());
writeFileSync(resolve(docsDir, 'simulation-results.md'), renderSimulationResults());

console.log(
  `Balance simulation written: ${phases.length} phases, ${profiles.length} profiles, ${rows.length} checkpoints.`,
);

function renderPhaseTargets() {
  const table = phases
    .map(
      (phase) =>
        `| ${phase.window} | ${phase.name} | ${phase.buds} | ${phase.bps} | ${phase.bpc} | ${phase.items} | ${phase.upgrades} | ${phase.research} | ${phase.events} | ${phase.seeds} | ${phase.prestige} | ${phase.activeShare} |`,
    )
    .join('\n');

  return `# Phase Targets: 2-20 Hour Release Curve

Generated by \`npm run balance:simulate\`.

| Window | Phase | Target Buds | Target BPS | Target BPC | Items | Upgrades | Research | Events | Seeds | Prestige | Active Share |
| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
${table}

## Balance Intent

- The first prestige should become visible around 60-90 minutes, but the first efficient prestige should usually happen after the player has seen research and multiple upgrade categories.
- Active clicking remains relevant through BPC, event catch-up, abilities, and achievement score, but idle production becomes the dominant long-run driver after several prestiges.
- Events are tuned as acceleration windows, not mandatory progression. A semi-idle profile remains within one major phase of an active profile.
- Offline gain uses persisted non-temporary BPS and a capped payout, so closing the tab during a short boost does not multiply the return window.
`;
}

function renderSimulationResults() {
  const table = rows
    .map(
      (row) =>
        `| ${row.profile} | ${row.minutes} | ${format(row.buds)} | ${format(row.bps)} | ${row.events} | ${row.seeds} | ${row.research} | ${row.prestigeCount} |`,
    )
    .join('\n');

  return `# Heuristic Balance Simulation Results

Generated by \`npm run balance:simulate\`. This is a lightweight release-owner pass, not a test suite.

| Profile | Minutes | Buds | BPS | Events | Seeds | Research | Prestiges |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
${table}

## Exploit Pass

| Risk | Release Decision |
| --- | --- |
| Offline gain during temporary BPS buffs | Persisted offline BPS strips event, ability and kickstart multipliers before save. |
| Event-seed spikes | Seed-heavy events are late-weighted and pity-controlled; rare events add excitement without replacing prestige. |
| Buy Max during cost buffs | Temporary cost multipliers are visible as active buffs; value is intentional but duration-limited. |
| Save import corruption | Import initializes and validates before overwriting storage. Invalid saves never replace the current save. |
| Achievement multiplier runaway | Achievement score bonus is capped at +6%, with only major achievements carrying extra tiny multipliers. |
| Early event skip | Event gating and category pity prevent the first two minutes from being decided by a single rare spawn. |

## Manual Playthrough Notes

- 30 minutes without prestige: first item, first upgrade, several item milestones, early events, and first research hints should all appear without a hard stop.
- First prestige run: target is 60-110 minutes depending on event engagement and active clicking. Prestige before the first research branch should be visibly inefficient.
- Second run: target speedup is roughly 1.6x-2.4x through prestige multiplier, early research, and stronger event handling.
- 4 hour run: player should be in repeated prestige planning with 25-40 research nodes and most shop identities understood.
- 10 hour run: late research, achievement score, cosmetics, and event specialization become the main motivators.
`;
}

function format(value) {
  if (value >= 1_000_000_000_000) {
    return `${(value / 1_000_000_000_000).toFixed(2)}T`;
  }
  if (value >= 1_000_000_000) {
    return `${(value / 1_000_000_000).toFixed(2)}B`;
  }
  if (value >= 1_000_000) {
    return `${(value / 1_000_000).toFixed(2)}M`;
  }
  if (value >= 1_000) {
    return `${(value / 1_000).toFixed(1)}k`;
  }
  return String(value);
}
